name: Asm

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest ]

    steps:
      - uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache-dependency-path: open_lessons/asm/go.sum
      - name: dependencies
        working-directory: ./open_lessons/asm
        run: go mod tidy
      - name: test
        working-directory: ./open_lessons/asm
        run: go test -v ./...
